### ISSUE TITLE
Would it be possible to add unlock device with only passcode or only touch id?

### ISSUE THREAD

**Issue by BeDaut** [cingulo/device_unlock#4]
Hello, your plugin is what I need and it works, but I need to ask user to unlock it with his passcode and not biometrics, is this possible?

**Comment by felipeespitalher** [comment]
Your desired behavior (passcode) is only available as a fallback to biometrics. At the moment we have no intention to avoid biometrics authentication. You would have to implement it.

**Comment by BeDaut** [comment]
Thanks for the fast and full reply @felipeespitalher, I'll do it myself then!
